### ISSUE TITLE
[TEST] Fix VCF output for truvari

### ISSUE THREAD

**Issue by eldariont** [seqan/iGenVar#127]
Benchmarking with truvari revealed two problems with our VCF output:
- [x] Genotype fields are missing: We need to add two columns (FORMAT and `<sample>`) where `<sample>` should be customizable by the user via a CLI parameter. Example:
```
#CHROM POS     ID        REF    ALT     QUAL FILTER INFO                              FORMAT      MYSAMPLE
20     14370   rs6054257 G      A       29   PASS   NS=3;DP=14;AF=0.5;DB;H2           GT          ./.
```

- [x] Connected to this, we need to define the format of the GT tag:
```
##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">
```

- [x] We need to add information about the reference contigs to the header. Example:
```
##contig=<ID=1,length=249250621>
##contig=<ID=2,length=243199373>
##contig=<ID=3,length=198022430>
```

**Comment by Irallia** [comment]
>     * We need to add information about the reference contigs to the header. Example:
> 
> 
> ```
> ##contig=<ID=1,length=249250621>
> ##contig=<ID=2,length=243199373>
> ##contig=<ID=3,length=198022430>
> ```

Do we get this information from the `@SQ` tag in the SAM file? I found this in the VCF spec:
```text
It is recommended in VCF and required in BCF that the header includes tags describing the reference and contigsbacking the data contained in the file.  These tags are based on the SQ field from the SAM spec; all tags are optional(see the VCF example above)
```
(https://samtools.github.io/hts-specs/VCFv4.3.pdf)

**Comment by eldariont** [comment]
> Do we get this information from the `@SQ` tag in the SAM file? I found this in the VCF spec:
> 
> ```
> It is recommended in VCF and required in BCF that the header includes tags describing the reference and contigsbacking the data contained in the file.  These tags are based on the SQ field from the SAM spec; all tags are optional(see the VCF example above)
> ```
> 
> (https://samtools.github.io/hts-specs/VCFv4.3.pdf)
Yes, we should be able to get this from the SQ field.

**Comment by Irallia** [comment]
What about the `FORMAT` line?
We added this in our first benchmark test aswell: 
` "##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">"`
Do you think we can skip this?

**Comment by eldariont** [comment]
> What about the `FORMAT` line?
> We added this in our first benchmark test aswell:
> ` "##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">"`
> Do you think we can skip this?

Good point! Yes, we need this line. I added it in the description above.
