### ISSUE TITLE
Extend the output option to decide if we want to write to a file and or to std::cout.

### ISSUE THREAD

**Issue by Irallia** [seqan/iGenVar#38]
This issue must be discussed: 

The question is, do we want to be able to choose whether we want to write an output file and or be able to write in std::cout aswell. The following review comment gives a general example and further information.

From a comment in https://github.com/seqan/iGenVar/pull/37#pullrequestreview-530999883
> May I suggest something that does not need to be changed or part of this PR:
> You go from functions `foo()` that print to std::cout to function `foo(std::ofstream & out_file)` that prints to a file. If you would do
> 
> ```c++
> template<typename stream_type>
> void foo(stream_type & stream)
> {
>     stream << // ...
> }
> ```
> 
> You can pass either a file OR std::cout. Writing to an dedicated output file is always very helpful in most application but I find sometimes, when writing pipelines, it can be very handy if the file can also be written to std::cout. This of course depends on your App and whether you think it may or may not be executed as part of a pipeline. If not you can ignore my suggestion, if so you might want to consider writing to `cout` unless a output_path is given. :) Just ideas
> 
> Note that there is also a output_stream seqan3 concept for checking that is has the `<<` operator.

**Comment by eldariont** [comment]
I think this would be very useful. In particular if we design our tool as a pipeline of smaller units instead of one monolithic application. If that is the case, we can chain the different units using unix pipes. In any way, it does not hurt to implement this kind of flexibility.
