### ISSUE TITLE
[FEATURE] Decouple junctions and a cluster of junctions

### ISSUE THREAD

**Issue by Irallia** [seqan/iGenVar#51]
After we added a first simple clustering method
eldariont left a comment:
> However, I think that the implementation of the simple clustering method (including the corresponding changes to the junction class) could be improved. Proviously, the junction class represented a single junction detected from a single read. Now, it is also used to represent clusters of junctions. IMO, we should represent clusters of junctions with a decouple junctions and cluster of junctions. or a std::vector. Then, we could keep all the cluster-related information, such as the number of supporting reads, the read names, etc. separated from the information on a single junction.

We would like to create this new class.

**Comment by eldariont** [comment]
I have drafted a new class `cluster` which represents a set of junctions. Before creating a PR I would like to run and update the tests but cannot due to the problem reported in https://github.com/seqan/iGenVar/issues/48.

@Irallia Should I create a PR nevertheless or wait for a fix to the test issue?

**Comment by Irallia** [comment]
> 
> 
> I have drafted a new class `cluster` which represents a set of junctions. Before creating a PR I would like to run and update the tests but cannot due to the problem reported in #48.
> 
> @Irallia Should I create a PR nevertheless or wait for a fix to the test issue?

I can checkout your branch and test it. Could you push your branch and give me the name?
I just noticed that we are not running our tests on Travis. I will try to set this up soon, that the tests are run online when you set a PR.
