### ISSUE TITLE
Method selection over CLI does not work properly

### ISSUE THREAD

**Issue by eldariont** [seqan/iGenVar#59]
Hi,

for me, the selection of specific junction detection methods (probably the same for clustering methods) via the CLI does not work properly. As introduced with https://github.com/seqan/iGenVar/pull/45, the set of methods to use can be specified via the `-m` option. But when I add `seqan3::debug_stream << args.methods << '\n';` after the argument parsing:

```
> build/bin/detect_breakends simulated.minimap2.hg19.coordsorted_cutoff.sam insertion_file_out.fasta -m1
[1,2,3,4,1]
...
The read pair method is not yet implemented.
The read depth method is not yet implemented.
...
```

Apparently, the parser just appends values to the already initialized `std::vector<uint8_t> methods{1, 2, 3, 4};` and executes all methods even though `-m1` was called.

Best
David

**Comment by Irallia** [comment]
I have already noticed the problem and have a solution lying around.
