### ISSUE TITLE
[INFRA] Combine two existing executables into a single monolithic executable

### ISSUE THREAD

**Issue by eldariont** [seqan/iGenVar#77]
**Original idea (2019):**
- Implementation of caller modules as separate executables
- Combination of modules with unix pipes, e.g. `./detect_breakends.cpp | ./find_deletions.cpp > output.vcf`

**Current plan (2021):**
- Implementation of caller modules in separate source files that are combined into a single large executable

**Therefore, we need to**
- Remove `find_deletions.cpp` executable and integrate code into the main executable (currently called `detect_breakends.cpp`)
- Update all associated tests
- Rename `detect_breakends.cpp` into something more generic like `iGenVar.cpp`

**Comment by Irallia** [comment]
Resolved by #81
